diagraph G {
  rankdir = "RL";
  node [shape = rect, fontname = "sans-serif"];
  "data.aws_ami.amzlinux2" [label="data.aws_ami.amzlinux2"];
  "aws_eip.bastion_eip" [label="aws_eip.bastion_eip"];
  "random_pet.this" [label="random_pet.this"];
  subgraph "cluster_module.ec2_public" {
    label = "module.ec2_public"
    fontname = "sans-serif"
    "module.ec2_public.data.aws_iam_policy_document.assume_role_policy" [label="data.aws_iam_policy_document.assume_role_policy"];
    "module.ec2_public.data.aws_partition.current" [label="data.aws_partition.current"];
    "module.ec2_public.data.aws_ssm_parameter.this" [label="data.aws_ssm_parameter.this"];
    "module.ec2_public.aws_iam_instance_profile.this" [label="aws_iam_instance_profile.this"];
    "module.ec2_public.aws_iam_role.this" [label="aws_iam_role.this"];
    "module.ec2_public.aws_iam_role_policy_attachment.this" [label="aws_iam_role_policy_attachment.this"];
    "module.ec2_public.aws_instance.ignore_ami" [label="aws_instance.ignore_ami"];      
    "module.ec2_public.aws_instance.this" [label="aws_instance.this"];
    "module.ec2_public.aws_spot_instance_request.this" [label="aws_spot_instance_request.this"];
  }
  subgraph "cluster_module.loadbalancer_sg" {
    label = "module.loadbalancer_sg"
    fontname = "sans-serif"
    "module.loadbalancer_sg.aws_security_group.this" [label="aws_security_group.this"]; 
    "module.loadbalancer_sg.aws_security_group.this_name_prefix" [label="aws_security_group.this_name_prefix"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_rules" [label="aws_security_group_rule.computed_egress_rules"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" [label="aws_security_group_rule.computed_egress_with_prefix_list_ids"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_self" [label="aws_security_group_rule.computed_egress_with_self"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" [label="aws_security_group_rule.computed_egress_with_source_security_group_id"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_rules" [label="aws_security_group_rule.computed_ingress_rules"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" [label="aws_security_group_rule.computed_ingress_with_prefix_list_ids"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_self" [label="aws_security_group_rule.computed_ingress_with_self"];
    "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" [label="aws_security_group_rule.computed_ingress_with_source_security_group_id"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_rules" [label="aws_security_group_rule.egress_rules"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_with_cidr_blocks" [label="aws_security_group_rule.egress_with_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.egress_with_ipv6_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_with_prefix_list_ids" [label="aws_security_group_rule.egress_with_prefix_list_ids"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_with_self" [label="aws_security_group_rule.egress_with_self"];
    "module.loadbalancer_sg.aws_security_group_rule.egress_with_source_security_group_id" [label="aws_security_group_rule.egress_with_source_security_group_id"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_rules" [label="aws_security_group_rule.ingress_rules"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_with_cidr_blocks" [label="aws_security_group_rule.ingress_with_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.ingress_with_ipv6_cidr_blocks"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_with_prefix_list_ids" [label="aws_security_group_rule.ingress_with_prefix_list_ids"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_with_self" [label="aws_security_group_rule.ingress_with_self"];
    "module.loadbalancer_sg.aws_security_group_rule.ingress_with_source_security_group_id" [label="aws_security_group_rule.ingress_with_source_security_group_id"];
  }
  subgraph "cluster_module.private_sg" {
    label = "module.private_sg"
    fontname = "sans-serif"
    "module.private_sg.aws_security_group.this" [label="aws_security_group.this"];      
    "module.private_sg.aws_security_group.this_name_prefix" [label="aws_security_group.this_name_prefix"];
    "module.private_sg.aws_security_group_rule.computed_egress_rules" [label="aws_security_group_rule.computed_egress_rules"];
    "module.private_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" [label="aws_security_group_rule.computed_egress_with_prefix_list_ids"];
    "module.private_sg.aws_security_group_rule.computed_egress_with_self" [label="aws_security_group_rule.computed_egress_with_self"];
    "module.private_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" [label="aws_security_group_rule.computed_egress_with_source_security_group_id"];  
    "module.private_sg.aws_security_group_rule.computed_ingress_rules" [label="aws_security_group_rule.computed_ingress_rules"];
    "module.private_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" [label="aws_security_group_rule.computed_ingress_with_prefix_list_ids"];
    "module.private_sg.aws_security_group_rule.computed_ingress_with_self" [label="aws_security_group_rule.computed_ingress_with_self"];
    "module.private_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" [label="aws_security_group_rule.computed_ingress_with_source_security_group_id"];
    "module.private_sg.aws_security_group_rule.egress_rules" [label="aws_security_group_rule.egress_rules"];
    "module.private_sg.aws_security_group_rule.egress_with_cidr_blocks" [label="aws_security_group_rule.egress_with_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.egress_with_ipv6_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.egress_with_prefix_list_ids" [label="aws_security_group_rule.egress_with_prefix_list_ids"];
    "module.private_sg.aws_security_group_rule.egress_with_self" [label="aws_security_group_rule.egress_with_self"];
    "module.private_sg.aws_security_group_rule.egress_with_source_security_group_id" [label="aws_security_group_rule.egress_with_source_security_group_id"];
    "module.private_sg.aws_security_group_rule.ingress_rules" [label="aws_security_group_rule.ingress_rules"];
    "module.private_sg.aws_security_group_rule.ingress_with_cidr_blocks" [label="aws_security_group_rule.ingress_with_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.ingress_with_ipv6_cidr_blocks"];
    "module.private_sg.aws_security_group_rule.ingress_with_prefix_list_ids" [label="aws_security_group_rule.ingress_with_prefix_list_ids"];
    "module.private_sg.aws_security_group_rule.ingress_with_self" [label="aws_security_group_rule.ingress_with_self"];
    "module.private_sg.aws_security_group_rule.ingress_with_source_security_group_id" [label="aws_security_group_rule.ingress_with_source_security_group_id"];
  }
  subgraph "cluster_module.public_bastion_sg" {
    label = "module.public_bastion_sg"
    fontname = "sans-serif"
    "module.public_bastion_sg.aws_security_group.this" [label="aws_security_group.this"];
    "module.public_bastion_sg.aws_security_group.this_name_prefix" [label="aws_security_group.this_name_prefix"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_rules" [label="aws_security_group_rule.computed_egress_rules"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" [label="aws_security_group_rule.computed_egress_with_prefix_list_ids"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_self" [label="aws_security_group_rule.computed_egress_with_self"];
    "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" [label="aws_security_group_rule.computed_egress_with_source_security_group_id"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_rules" [label="aws_security_group_rule.computed_ingress_rules"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" [label="aws_security_group_rule.computed_ingress_with_prefix_list_ids"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_self" [label="aws_security_group_rule.computed_ingress_with_self"];
    "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" [label="aws_security_group_rule.computed_ingress_with_source_security_group_id"];
    "module.public_bastion_sg.aws_security_group_rule.egress_rules" [label="aws_security_group_rule.egress_rules"];
    "module.public_bastion_sg.aws_security_group_rule.egress_with_cidr_blocks" [label="aws_security_group_rule.egress_with_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.egress_with_ipv6_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.egress_with_prefix_list_ids" [label="aws_security_group_rule.egress_with_prefix_list_ids"];
    "module.public_bastion_sg.aws_security_group_rule.egress_with_self" [label="aws_security_group_rule.egress_with_self"];
    "module.public_bastion_sg.aws_security_group_rule.egress_with_source_security_group_id" [label="aws_security_group_rule.egress_with_source_security_group_id"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_rules" [label="aws_security_group_rule.ingress_rules"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_with_cidr_blocks" [label="aws_security_group_rule.ingress_with_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" [label="aws_security_group_rule.ingress_with_ipv6_cidr_blocks"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_with_prefix_list_ids" [label="aws_security_group_rule.ingress_with_prefix_list_ids"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_with_self" [label="aws_security_group_rule.ingress_with_self"];
    "module.public_bastion_sg.aws_security_group_rule.ingress_with_source_security_group_id" [label="aws_security_group_rule.ingress_with_source_security_group_id"];
  }
  subgraph "cluster_module.vpc" {
    label = "module.vpc"
    fontname = "sans-serif"
    "module.vpc.data.aws_iam_policy_document.flow_log_cloudwatch_assume_role" [label="data.aws_iam_policy_document.flow_log_cloudwatch_assume_role"];
    "module.vpc.data.aws_iam_policy_document.vpc_flow_log_cloudwatch" [label="data.aws_iam_policy_document.vpc_flow_log_cloudwatch"];
    "module.vpc.aws_cloudwatch_log_group.flow_log" [label="aws_cloudwatch_log_group.flow_log"];
    "module.vpc.aws_customer_gateway.this" [label="aws_customer_gateway.this"];
    "module.vpc.aws_db_subnet_group.database" [label="aws_db_subnet_group.database"];   
    "module.vpc.aws_default_network_acl.this" [label="aws_default_network_acl.this"];   
    "module.vpc.aws_default_route_table.default" [label="aws_default_route_table.default"];
    "module.vpc.aws_default_security_group.this" [label="aws_default_security_group.this"];
    "module.vpc.aws_default_vpc.this" [label="aws_default_vpc.this"];
    "module.vpc.aws_egress_only_internet_gateway.this" [label="aws_egress_only_internet_gateway.this"];
    "module.vpc.aws_eip.nat" [label="aws_eip.nat"];
    "module.vpc.aws_elasticache_subnet_group.elasticache" [label="aws_elasticache_subnet_group.elasticache"];
    "module.vpc.aws_flow_log.this" [label="aws_flow_log.this"];
    "module.vpc.aws_iam_policy.vpc_flow_log_cloudwatch" [label="aws_iam_policy.vpc_flow_log_cloudwatch"];
    "module.vpc.aws_iam_role.vpc_flow_log_cloudwatch" [label="aws_iam_role.vpc_flow_log_cloudwatch"];
    "module.vpc.aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch" [label="aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch"];
    "module.vpc.aws_internet_gateway.this" [label="aws_internet_gateway.this"];
    "module.vpc.aws_nat_gateway.this" [label="aws_nat_gateway.this"];
    "module.vpc.aws_network_acl.database" [label="aws_network_acl.database"];
    "module.vpc.aws_network_acl.elasticache" [label="aws_network_acl.elasticache"];     
    "module.vpc.aws_network_acl.intra" [label="aws_network_acl.intra"];
    "module.vpc.aws_network_acl.outpost" [label="aws_network_acl.outpost"];
    "module.vpc.aws_network_acl.private" [label="aws_network_acl.private"];
    "module.vpc.aws_network_acl.public" [label="aws_network_acl.public"];
    "module.vpc.aws_network_acl.redshift" [label="aws_network_acl.redshift"];
    "module.vpc.aws_network_acl_rule.database_inbound" [label="aws_network_acl_rule.database_inbound"];
    "module.vpc.aws_network_acl_rule.database_outbound" [label="aws_network_acl_rule.database_outbound"];
    "module.vpc.aws_network_acl_rule.elasticache_inbound" [label="aws_network_acl_rule.elasticache_inbound"];
    "module.vpc.aws_network_acl_rule.elasticache_outbound" [label="aws_network_acl_rule.elasticache_outbound"];
    "module.vpc.aws_network_acl_rule.intra_inbound" [label="aws_network_acl_rule.intra_inbound"];
    "module.vpc.aws_network_acl_rule.intra_outbound" [label="aws_network_acl_rule.intra_outbound"];
    "module.vpc.aws_network_acl_rule.outpost_inbound" [label="aws_network_acl_rule.outpost_inbound"];
    "module.vpc.aws_network_acl_rule.outpost_outbound" [label="aws_network_acl_rule.outpost_outbound"];
    "module.vpc.aws_network_acl_rule.private_inbound" [label="aws_network_acl_rule.private_inbound"];
    "module.vpc.aws_network_acl_rule.private_outbound" [label="aws_network_acl_rule.private_outbound"];
    "module.vpc.aws_network_acl_rule.public_inbound" [label="aws_network_acl_rule.public_inbound"];
    "module.vpc.aws_network_acl_rule.public_outbound" [label="aws_network_acl_rule.public_outbound"];
    "module.vpc.aws_network_acl_rule.redshift_inbound" [label="aws_network_acl_rule.redshift_inbound"];
    "module.vpc.aws_network_acl_rule.redshift_outbound" [label="aws_network_acl_rule.redshift_outbound"];
    "module.vpc.aws_redshift_subnet_group.redshift" [label="aws_redshift_subnet_group.redshift"];
    "module.vpc.aws_route.database_dns64_nat_gateway" [label="aws_route.database_dns64_nat_gateway"];
    "module.vpc.aws_route.database_internet_gateway" [label="aws_route.database_internet_gateway"];
    "module.vpc.aws_route.database_ipv6_egress" [label="aws_route.database_ipv6_egress"];
    "module.vpc.aws_route.database_nat_gateway" [label="aws_route.database_nat_gateway"];
    "module.vpc.aws_route.private_dns64_nat_gateway" [label="aws_route.private_dns64_nat_gateway"];
    "module.vpc.aws_route.private_ipv6_egress" [label="aws_route.private_ipv6_egress"]; 
    "module.vpc.aws_route.private_nat_gateway" [label="aws_route.private_nat_gateway"]; 
    "module.vpc.aws_route.public_internet_gateway" [label="aws_route.public_internet_gateway"];
    "module.vpc.aws_route.public_internet_gateway_ipv6" [label="aws_route.public_internet_gateway_ipv6"];
    "module.vpc.aws_route_table.database" [label="aws_route_table.database"];
    "module.vpc.aws_route_table.elasticache" [label="aws_route_table.elasticache"];     
    "module.vpc.aws_route_table.intra" [label="aws_route_table.intra"];
    "module.vpc.aws_route_table.private" [label="aws_route_table.private"];
    "module.vpc.aws_route_table.public" [label="aws_route_table.public"];
    "module.vpc.aws_route_table.redshift" [label="aws_route_table.redshift"];
    "module.vpc.aws_route_table_association.database" [label="aws_route_table_association.database"];
    "module.vpc.aws_route_table_association.elasticache" [label="aws_route_table_association.elasticache"];
    "module.vpc.aws_route_table_association.intra" [label="aws_route_table_association.intra"];
    "module.vpc.aws_route_table_association.outpost" [label="aws_route_table_association.outpost"];
    "module.vpc.aws_route_table_association.private" [label="aws_route_table_association.private"];
    "module.vpc.aws_route_table_association.public" [label="aws_route_table_association.public"];
    "module.vpc.aws_route_table_association.redshift" [label="aws_route_table_association.redshift"];
    "module.vpc.aws_route_table_association.redshift_public" [label="aws_route_table_association.redshift_public"];
    "module.vpc.aws_subnet.database" [label="aws_subnet.database"];
    "module.vpc.aws_subnet.elasticache" [label="aws_subnet.elasticache"];
    "module.vpc.aws_subnet.intra" [label="aws_subnet.intra"];
    "module.vpc.aws_subnet.outpost" [label="aws_subnet.outpost"];
    "module.vpc.aws_subnet.private" [label="aws_subnet.private"];
    "module.vpc.aws_subnet.public" [label="aws_subnet.public"];
    "module.vpc.aws_subnet.redshift" [label="aws_subnet.redshift"];
    "module.vpc.aws_vpc.this" [label="aws_vpc.this"];
    "module.vpc.aws_vpc_dhcp_options.this" [label="aws_vpc_dhcp_options.this"];
    "module.vpc.aws_vpc_dhcp_options_association.this" [label="aws_vpc_dhcp_options_association.this"];
    "module.vpc.aws_vpc_ipv4_cidr_block_association.this" [label="aws_vpc_ipv4_cidr_block_association.this"];
    "module.vpc.aws_vpn_gateway.this" [label="aws_vpn_gateway.this"];
    "module.vpc.aws_vpn_gateway_attachment.this" [label="aws_vpn_gateway_attachment.this"];
    "module.vpc.aws_vpn_gateway_route_propagation.intra" [label="aws_vpn_gateway_route_propagation.intra"];
    "module.vpc.aws_vpn_gateway_route_propagation.private" [label="aws_vpn_gateway_route_propagation.private"];
    "module.vpc.aws_vpn_gateway_route_propagation.public" [label="aws_vpn_gateway_route_propagation.public"];
  }
  "aws_eip.bastion_eip" -> "module.ec2_public.aws_iam_role_policy_attachment.this";     
  "aws_eip.bastion_eip" -> "module.ec2_public.aws_instance.ignore_ami";
  "aws_eip.bastion_eip" -> "module.ec2_public.aws_instance.this";
  "aws_eip.bastion_eip" -> "module.ec2_public.aws_spot_instance_request.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_customer_gateway.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_db_subnet_group.database";
  "aws_eip.bastion_eip" -> "module.vpc.aws_default_network_acl.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_default_route_table.default";
  "aws_eip.bastion_eip" -> "module.vpc.aws_default_security_group.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_default_vpc.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_elasticache_subnet_group.elasticache";       
  "aws_eip.bastion_eip" -> "module.vpc.aws_flow_log.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.database_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.database_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.elasticache_inbound";       
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.elasticache_outbound";      
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.intra_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.intra_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.outpost_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.outpost_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.private_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.private_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.public_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.public_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.redshift_inbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_network_acl_rule.redshift_outbound";
  "aws_eip.bastion_eip" -> "module.vpc.aws_redshift_subnet_group.redshift";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.database_dns64_nat_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.database_internet_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.database_ipv6_egress";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.database_nat_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.private_dns64_nat_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.private_ipv6_egress";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.private_nat_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.public_internet_gateway";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route.public_internet_gateway_ipv6";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.database";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.elasticache";        
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.intra";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.outpost";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.private";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.public";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.redshift";
  "aws_eip.bastion_eip" -> "module.vpc.aws_route_table_association.redshift_public";    
  "aws_eip.bastion_eip" -> "module.vpc.aws_vpc_dhcp_options_association.this";
  "aws_eip.bastion_eip" -> "module.vpc.aws_vpn_gateway_route_propagation.intra";        
  "aws_eip.bastion_eip" -> "module.vpc.aws_vpn_gateway_route_propagation.private";      
  "aws_eip.bastion_eip" -> "module.vpc.aws_vpn_gateway_route_propagation.public";       
  "module.ec2_public.data.aws_iam_policy_document.assume_role_policy" -> "module.ec2_public.data.aws_partition.current";
  "module.ec2_public.data.aws_ssm_parameter.this" -> "data.aws_ami.amzlinux2";
  "module.ec2_public.aws_iam_instance_profile.this" -> "module.ec2_public.aws_iam_role.this";
  "module.ec2_public.aws_iam_role.this" -> "module.ec2_public.data.aws_iam_policy_document.assume_role_policy";
  "module.ec2_public.aws_iam_role_policy_attachment.this" -> "module.ec2_public.aws_iam_role.this";
  "module.ec2_public.aws_instance.ignore_ami" -> "module.ec2_public.data.aws_ssm_parameter.this";
  "module.ec2_public.aws_instance.ignore_ami" -> "module.ec2_public.aws_iam_instance_profile.this";
  "module.ec2_public.aws_instance.ignore_ami" -> "module.public_bastion_sg.aws_security_group.this";
  "module.ec2_public.aws_instance.ignore_ami" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.ec2_public.aws_instance.ignore_ami" -> "module.vpc.aws_subnet.public";        
  "module.ec2_public.aws_instance.this" -> "module.ec2_public.data.aws_ssm_parameter.this";
  "module.ec2_public.aws_instance.this" -> "module.ec2_public.aws_iam_instance_profile.this";
  "module.ec2_public.aws_instance.this" -> "module.public_bastion_sg.aws_security_group.this";
  "module.ec2_public.aws_instance.this" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.ec2_public.aws_instance.this" -> "module.vpc.aws_subnet.public";
  "module.ec2_public.aws_spot_instance_request.this" -> "module.ec2_public.data.aws_ssm_parameter.this";
  "module.ec2_public.aws_spot_instance_request.this" -> "module.ec2_public.aws_iam_instance_profile.this";
  "module.ec2_public.aws_spot_instance_request.this" -> "module.public_bastion_sg.aws_security_group.this";
  "module.ec2_public.aws_spot_instance_request.this" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.ec2_public.aws_spot_instance_request.this" -> "module.vpc.aws_subnet.public"; 
  "module.loadbalancer_sg.aws_security_group.this" -> "module.vpc.aws_vpc.this";        
  "module.loadbalancer_sg.aws_security_group.this_name_prefix" -> "module.vpc.aws_vpc.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_rules" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_rules" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_self" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_self" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_rules" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_rules" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_rules" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_rules" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_self" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_self" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_rules" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_rules" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_self" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_self" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this";
  "module.loadbalancer_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.loadbalancer_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group.this" -> "module.vpc.aws_vpc.this";
  "module.private_sg.aws_security_group.this_name_prefix" -> "module.vpc.aws_vpc.this"; 
  "module.private_sg.aws_security_group_rule.computed_egress_rules" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_rules" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_egress_with_self" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_with_self" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_rules" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_rules" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_rules" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_rules" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_with_self" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_with_self" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_rules" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_rules" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_with_self" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_with_self" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.private_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this";
  "module.private_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.private_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group.this" -> "module.vpc.aws_vpc.this";      
  "module.public_bastion_sg.aws_security_group.this_name_prefix" -> "module.vpc.aws_vpc.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_rules" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_rules" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_self" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_self" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_egress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_rules" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_rules" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_self" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_rules" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_rules" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_self" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_self" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.egress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_rules" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_rules" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_ipv6_cidr_blocks" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_prefix_list_ids" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_self" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_self" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this";
  "module.public_bastion_sg.aws_security_group_rule.ingress_with_source_security_group_id" -> "module.public_bastion_sg.aws_security_group.this_name_prefix";
  "module.vpc.aws_cloudwatch_log_group.flow_log" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_db_subnet_group.database" -> "module.vpc.aws_subnet.database";        
  "module.vpc.aws_default_network_acl.this" -> "module.vpc.aws_vpc.this";
  "module.vpc.aws_default_route_table.default" -> "module.vpc.aws_vpc.this";
  "module.vpc.aws_default_security_group.this" -> "module.vpc.aws_vpc.this";
  "module.vpc.aws_egress_only_internet_gateway.this" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_eip.nat" -> "module.vpc.aws_internet_gateway.this";
  "module.vpc.aws_elasticache_subnet_group.elasticache" -> "module.vpc.aws_subnet.elasticache";
  "module.vpc.aws_flow_log.this" -> "module.vpc.aws_cloudwatch_log_group.flow_log";     
  "module.vpc.aws_flow_log.this" -> "module.vpc.aws_iam_role.vpc_flow_log_cloudwatch";  
  "module.vpc.aws_iam_policy.vpc_flow_log_cloudwatch" -> "module.vpc.data.aws_iam_policy_document.vpc_flow_log_cloudwatch";
  "module.vpc.aws_iam_role.vpc_flow_log_cloudwatch" -> "module.vpc.data.aws_iam_policy_document.flow_log_cloudwatch_assume_role";
  "module.vpc.aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch" -> "module.vpc.aws_iam_policy.vpc_flow_log_cloudwatch";
  "module.vpc.aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch" -> "module.vpc.aws_iam_role.vpc_flow_log_cloudwatch";
  "module.vpc.aws_internet_gateway.this" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_nat_gateway.this" -> "module.vpc.aws_eip.nat";
  "module.vpc.aws_nat_gateway.this" -> "module.vpc.aws_subnet.public";
  "module.vpc.aws_network_acl.database" -> "module.vpc.aws_subnet.database";
  "module.vpc.aws_network_acl.elasticache" -> "module.vpc.aws_subnet.elasticache";      
  "module.vpc.aws_network_acl.intra" -> "module.vpc.aws_subnet.intra";
  "module.vpc.aws_network_acl.outpost" -> "module.vpc.aws_subnet.outpost";
  "module.vpc.aws_network_acl.private" -> "module.vpc.aws_subnet.private";
  "module.vpc.aws_network_acl.public" -> "module.vpc.aws_subnet.public";
  "module.vpc.aws_network_acl.redshift" -> "module.vpc.aws_subnet.redshift";
  "module.vpc.aws_network_acl_rule.database_inbound" -> "module.vpc.aws_network_acl.database";
  "module.vpc.aws_network_acl_rule.database_outbound" -> "module.vpc.aws_network_acl.database";
  "module.vpc.aws_network_acl_rule.elasticache_inbound" -> "module.vpc.aws_network_acl.elasticache";
  "module.vpc.aws_network_acl_rule.elasticache_outbound" -> "module.vpc.aws_network_acl.elasticache";
  "module.vpc.aws_network_acl_rule.intra_inbound" -> "module.vpc.aws_network_acl.intra";
  "module.vpc.aws_network_acl_rule.intra_outbound" -> "module.vpc.aws_network_acl.intra";
  "module.vpc.aws_network_acl_rule.outpost_inbound" -> "module.vpc.aws_network_acl.outpost";
  "module.vpc.aws_network_acl_rule.outpost_outbound" -> "module.vpc.aws_network_acl.outpost";
  "module.vpc.aws_network_acl_rule.private_inbound" -> "module.vpc.aws_network_acl.private";
  "module.vpc.aws_network_acl_rule.private_outbound" -> "module.vpc.aws_network_acl.private";
  "module.vpc.aws_network_acl_rule.public_inbound" -> "module.vpc.aws_network_acl.public";
  "module.vpc.aws_network_acl_rule.public_outbound" -> "module.vpc.aws_network_acl.public";
  "module.vpc.aws_network_acl_rule.redshift_inbound" -> "module.vpc.aws_network_acl.redshift";
  "module.vpc.aws_network_acl_rule.redshift_outbound" -> "module.vpc.aws_network_acl.redshift";
  "module.vpc.aws_redshift_subnet_group.redshift" -> "module.vpc.aws_subnet.redshift";  
  "module.vpc.aws_route.database_dns64_nat_gateway" -> "module.vpc.aws_nat_gateway.this";
  "module.vpc.aws_route.database_dns64_nat_gateway" -> "module.vpc.aws_route_table.database";
  "module.vpc.aws_route.database_internet_gateway" -> "module.vpc.aws_internet_gateway.this";
  "module.vpc.aws_route.database_internet_gateway" -> "module.vpc.aws_route_table.database";
  "module.vpc.aws_route.database_ipv6_egress" -> "module.vpc.aws_egress_only_internet_gateway.this";
  "module.vpc.aws_route.database_ipv6_egress" -> "module.vpc.aws_route_table.database"; 
  "module.vpc.aws_route.database_nat_gateway" -> "module.vpc.aws_nat_gateway.this";     
  "module.vpc.aws_route.database_nat_gateway" -> "module.vpc.aws_route_table.database"; 
  "module.vpc.aws_route.private_dns64_nat_gateway" -> "module.vpc.aws_nat_gateway.this";
  "module.vpc.aws_route.private_dns64_nat_gateway" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route.private_ipv6_egress" -> "module.vpc.aws_egress_only_internet_gateway.this";
  "module.vpc.aws_route.private_ipv6_egress" -> "module.vpc.aws_route_table.private";   
  "module.vpc.aws_route.private_nat_gateway" -> "module.vpc.aws_nat_gateway.this";      
  "module.vpc.aws_route.private_nat_gateway" -> "module.vpc.aws_route_table.private";   
  "module.vpc.aws_route.public_internet_gateway" -> "module.vpc.aws_internet_gateway.this";
  "module.vpc.aws_route.public_internet_gateway" -> "module.vpc.aws_route_table.public";
  "module.vpc.aws_route.public_internet_gateway_ipv6" -> "module.vpc.aws_internet_gateway.this";
  "module.vpc.aws_route.public_internet_gateway_ipv6" -> "module.vpc.aws_route_table.public";
  "module.vpc.aws_route_table.database" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table.elasticache" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table.intra" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table.private" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table.public" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table.redshift" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_route_table_association.database" -> "module.vpc.aws_route_table.database";
  "module.vpc.aws_route_table_association.database" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route_table_association.database" -> "module.vpc.aws_subnet.database";
  "module.vpc.aws_route_table_association.elasticache" -> "module.vpc.aws_route_table.elasticache";
  "module.vpc.aws_route_table_association.elasticache" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route_table_association.elasticache" -> "module.vpc.aws_subnet.elasticache";
  "module.vpc.aws_route_table_association.intra" -> "module.vpc.aws_route_table.intra"; 
  "module.vpc.aws_route_table_association.intra" -> "module.vpc.aws_subnet.intra";      
  "module.vpc.aws_route_table_association.outpost" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route_table_association.outpost" -> "module.vpc.aws_subnet.outpost";  
  "module.vpc.aws_route_table_association.private" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route_table_association.private" -> "module.vpc.aws_subnet.private";  
  "module.vpc.aws_route_table_association.public" -> "module.vpc.aws_route_table.public";
  "module.vpc.aws_route_table_association.public" -> "module.vpc.aws_subnet.public";    
  "module.vpc.aws_route_table_association.redshift" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_route_table_association.redshift" -> "module.vpc.aws_route_table.redshift";
  "module.vpc.aws_route_table_association.redshift" -> "module.vpc.aws_subnet.redshift";
  "module.vpc.aws_route_table_association.redshift_public" -> "module.vpc.aws_route_table.public";
  "module.vpc.aws_route_table_association.redshift_public" -> "module.vpc.aws_route_table.redshift";
  "module.vpc.aws_route_table_association.redshift_public" -> "module.vpc.aws_subnet.redshift";
  "module.vpc.aws_subnet.database" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.elasticache" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.intra" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.outpost" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.private" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.public" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_subnet.redshift" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_vpc_dhcp_options_association.this" -> "module.vpc.aws_vpc_dhcp_options.this";
  "module.vpc.aws_vpc_dhcp_options_association.this" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_vpc_ipv4_cidr_block_association.this" -> "module.vpc.aws_vpc.this";   
  "module.vpc.aws_vpn_gateway.this" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_vpn_gateway_attachment.this" -> "module.vpc.aws_vpc_ipv4_cidr_block_association.this";
  "module.vpc.aws_vpn_gateway_route_propagation.intra" -> "module.vpc.aws_route_table.intra";
  "module.vpc.aws_vpn_gateway_route_propagation.intra" -> "module.vpc.aws_vpn_gateway.this";
  "module.vpc.aws_vpn_gateway_route_propagation.intra" -> "module.vpc.aws_vpn_gateway_attachment.this";
  "module.vpc.aws_vpn_gateway_route_propagation.private" -> "module.vpc.aws_route_table.private";
  "module.vpc.aws_vpn_gateway_route_propagation.private" -> "module.vpc.aws_vpn_gateway.this";
  "module.vpc.aws_vpn_gateway_route_propagation.private" -> "module.vpc.aws_vpn_gateway_attachment.this";
  "module.vpc.aws_vpn_gateway_route_propagation.public" -> "module.vpc.aws_route_table.public";
  "module.vpc.aws_vpn_gateway_route_propagation.public" -> "module.vpc.aws_vpn_gateway.this";
  "module.vpc.aws_vpn_gateway_route_propagation.public" -> "module.vpc.aws_vpn_gateway_attachment.this";
}
